### ISSUE TITLE
Durability Check

### ISSUE THREAD

**Issue by bagzli** [f90/RaidInviteClassic#20] opened 2021-07-28 23:36 UTC
[19:29] RaidInviteClassic: WARNING: Durability could not be checked for Gobstop-Herod. Player is offline or doesnt have RIC/DBM installed?

Many of my players have DBM and yet I get this message for them. How do we get the addon to work for them? Also is same possible for BigWigs?

**Comment by f90** [comment] 2021-07-29 15:17
Please try out version 2.4.2, should be fixed there, and report back here! I updated the version of the library that does the durability checking, DBM has a new one than the one included in RIC.

**Comment by bagzli** [comment] 2021-08-01 00:41
the overwolf says im up to date, how do I check the actual version i'm on?

**Comment by f90** [comment] 2021-08-01 01:03
You can type 
`/ric version`
in chat

**Comment by bagzli** [comment] 2021-08-01 04:05
On 2.4.2. Not sure when this was pushed but I had issues 3 days ago when I originally posted this. I'll test again on tuesday.

**Comment by f90** [comment] 2021-08-09 00:26
Closing this for now assuming this works now. Otherwise please reopen!

**Comment by bagzli** [comment] 2021-08-10 23:35
This is still a problem. Several of my guys have DBM installed and yet I still get this:

[19:34] RaidInviteClassic: WARNING: Durability could not be checked for Player-Server. Player is offline, doesnt have RIC/DBM installed, or a different LibDurability version.

**Comment by bagzli** [comment] 2021-08-11 14:42
@f90 just making sure you see this as the ticket sits as closed and I can't re-open

**Comment by f90** [comment] 2021-08-12 12:20
I think I found a problem about how the player names were handled. The durability addon seems to sometimes gives us "player", sometimes "player-server" format for the durability info. So my addon was waiting for info for "player-server" but didn't get any (ignored "player"). I made sure that I convert every name to "player-server" everywhere first.

Can you download the code from 
https://github.com/f90/RaidInviteClassic/tree/durability_name_fix
and paste it into the RaidInviteClassic folder to test whether the problem still occurs? You can overwrite already existing files. If it all works, I will release it to the public, then you just need to make sure your updater app brings you onto the normal update channel again and discards the "local changes" you made. This way you can beta-test it for the whole community and we can get rid of potential new bugs before everyone has to suffer from them :) Thanks :)

**Comment by bagzli** [comment] 2021-08-17 23:35
Ok, I'll get it and try it tomorrow.

**Comment by bagzli** [comment] 2021-08-19 23:30
Sorry, was not able to test this last night. My next big raid is on Wednesday next week.

**Comment by bagzli** [comment] 2021-08-25 23:33
Good news, the repair whispers go out now. Thanks for fixing it. Can you let me know when its on live so I can delete and reinstall the addon and get normal updates moving forward.

**Comment by bagzli** [comment] 2021-08-25 23:34
I wanted to make one suggestion though, allow us to set a threshold for repairs. For example if I am ok with somebody being 99% instead of whispering everyone who is 99%.

**Comment by bagzli** [comment] 2021-08-25 23:49
One potential bug, had a guy in my raid a whisper go out that he is at 75% repaired. He sent a screenshot and he was fully repaired.

Had another guy sent whisper to him that he is 99% but he was 92%.

Third guy whisper said 78% but he was 75%.

They had DBM installed but not RIC. The third guy had RIC installed and Big Wigs instead of DBM.

**Comment by f90** [comment] 2021-08-30 20:00
Good to see that it works again!
People having lower durability than you reported to them is because we measure the average gear durability, they are probably looking at the minimum gear durability. Just a small detail there but still everything works as expected.

Why someone was notified that he was 75% repaired but he was fully repaired I cannot tell you to be honest, never had this issue occur. If you can find a way to reproduce the error let me know... Potentially he has some items in his inventory that are not fully repaired and are counted into the calculation somehow? Just a guess

Just reply if you find out more or have the issue again in the future!

**Closed as completed by f90** 2021-08-30 20:00 UTC
