### ISSUE TITLE
Problem & Suggestion

### ISSUE THREAD

**Issue by bagzli** [f90/RaidInviteClassic#16] opened 2021-06-19 23:14 UTC
I was playing around with the whole Arrange raid button and it kept crashing for me saying how a manual arrange got in the way

[19:11] RaidInviteClassic: ERROR: Our group swap was interrupted by a remote swap. Stopping...

However, there was just 3 people in the raid and it wouldn't work, I was the raid leader so I had the permission. It would move the hunter to group 3, but not the paladin. After that the addon gets very wonky.

I also wanted to suggest to make this a lot easier to use as you have to go through 2 menus in order to click the arrange groups button. Would it a lot nicer if we could get a little dropdown in the raid menu where we can click suggested roster and then it arranges it like that. Basically the way the Raid Group Organizer addon works. Would be great if I could achieve the same functionality with this addon that you get in the other as oppose to have to use them both.

**Comment by f90** [comment] 2021-06-20 01:57
Hey, check out the new v2.3.2 version and please come back here to tell me whether that fixed your issue, I am pretty sure I found the cause.

As to your suggestion, hover your mouse over the RIC minimap icon to see shortcuts. You can rightclick on it to quick-switch between rosters/group setups. Ctrl+Left click starts group arrangement directly. So this is already implemented :)

**Comment by bagzli** [comment] 2021-06-20 02:44
So the selected roster is grayed out when I click on the button on mini map, so I can't force it to start group arrangement.

**Comment by bagzli** [comment] 2021-06-20 02:47
The re-arranging seems to work now! just a bit slow. The other addon I was using seemed to be instant, also would warn which users are missing. Don't mean to say your addon is inferior, just pointing out some of the things I liked from the other. I still would much rather use yours as a one add on solution.

**Comment by bagzli** [comment] 2021-06-20 02:49
OH! I figured out the shortcut for auto sort from the icon, sorry I didn't realize I click on the icon, thought I was suppose to click on the team. So this works as well now!

**Comment by f90** [comment] 2021-06-20 22:03
Hey, good to hear. I implemented a fast version of group swapping and it prints players in your group setup that are not in the raid as warning into your console (although you can also see that in the group window due to the status icons next to the players). Could you beta-test it for me whether it works without bugs? Since it's completely rewritten I don't want to release it to everyone unless someone uses it for some actual groups.

To test it, check out the tbc-fastgroup branch - download the code here as ZIP file, then extract it into the RaidInviteClassic folder in your addons folder (overwriting the old files in the process):

https://github.com/f90/RaidInviteClassic/tree/tbc-fastgroup

**Comment by f90** [comment] 2021-06-21 17:50
@bagzli Is the version from 
https://github.com/f90/RaidInviteClassic/tree/tbc-fastgroup
working for you in terms of group switching? Did you manage to test it on a big raid and didnt encounter any errors? Would be very useful to know so I can merge it and make it available to all. Thanks.

**Comment by bagzli** [comment] 2021-06-21 19:22
I have a raid on Wednesday, will test then.

**Comment by bagzli** [comment] 2021-06-22 23:20
Tested it today on a 10 man group with 9/10 people in the raid and it was instant switching for all 9 members and for the 10th member from group 1 that was missing the spot was left empty and I got notified in chat that this person was missing. Will test 25 man tomorrow.

**Comment by bagzli** [comment] 2021-06-23 17:01
One thing I noticed is that there is this "Default Roster" that I can't get rid of. I tried renaming it but it just comes back as a new roster. Would be nice not having to have that in there but instead just be able to mark one of the rosters as default if you need default for some logic.

Still have not done my raid today, will post tonight on how sorting went.

**Comment by bagzli** [comment] 2021-06-23 23:55
One other thing I want to note is that we sometimes start invites like half an hour early and as people log on, when they are ready they send us a whisper and join. This part works with your addon with exception of when I click start invites it attempts to invite all 24 players. Would be nice to skip that step and just have the guild message sent out without actually not sending the invites and also having the ability to disable the interval altogether.

As for testing, I have finished tonight and fast invites seem to work really well, I've had no issues and missing players were printed out in chat. Just one problem, even though it arranged everyone, it kept saying that raid is not arranged.

[19:54] RaidInviteClassic: REARRANGING...
[19:54] RaidInviteClassic: RAID IS NOT ARRANGED

**Comment by f90** [comment] 2021-06-24 18:08
For your other problem, I will open a different issue here! Thanks for that suggestion. It's not too hard to put that in as a setting to activate and deactivate the initial invites or all invites during the invite phase.

One final thing, could you update to public v2.3.3 and check it out one final time? I put a delay between switching and outputting the result in console, so it should now say "Raid is arranged" and not the opposite by mistake, which I think happened because if you immediately check the groups of all players, they are not updated yet since the switch commands have not taken effect yet.

**Comment by bagzli** [comment] 2021-06-26 00:08
Yeah, I will but next raid is not till wednesday again.

**Comment by f90** [comment] 2021-06-30 12:14
@bagzli Thanks, I just released the v2.3.3 version with fast group switching in it on curseforge, please make sure to update to that version before you start the raid later. Have fun raiding!

**Comment by bagzli** [comment] 2021-06-30 23:48
It worked, but it did not print out missing players in chat like it use to.

**Comment by bagzli** [comment] 2021-06-30 23:52
Ok, correction. I thought it worked. I was using the shortcut from mini map and it said raid was arranged but when I double checked, it was not correct. Then I opened the group assignments window and clicked the button there and then it worked and also listed out the missing players.

**Comment by f90** [comment] 2021-07-01 16:54
That is very strange, the minimap functionality is almost exactly identical to the group window button. Maybe you can describe a test case in which this error always occurs so I can debug it, until then I don't think I am able to fix this since after looking at the code I don't see any mistakes...

**Comment by f90** [comment] 2021-07-01 16:55
The function to detect whether the raid is already arranged is also the same, in both cases getArrangeStatus is called, which calls sortGroup(true) to check group setup

**Comment by f90** [comment] 2021-07-12 01:05
Can't replicate the issue, seems like it's working fine on my end -> Closing this for now.

**Closed as completed by f90** 2021-07-12 01:05 UTC
Labels: bug, enhancement
